// Package sheet renders and stores per-tool cheatsheets as plain markdown
// files the user owns and can edit.
package sheet

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/antosec/ricorda/internal/analyze"
	"github.com/antosec/ricorda/internal/paths"
	"github.com/antosec/ricorda/internal/project"
)

// KeepMarker separates the generated part of a sheet from the user's own
// notes. Everything below it survives rescans.
const KeepMarker = "<!-- ricorda:keep -->"

const defaultKeep = KeepMarker + `
## Your notes

Anything below the keep-marker survives rescans. Make it yours.
`

// Dir returns the ricorda home directory ($RICORDA_HOME or ~/.ricorda).
func Dir() (string, error) {
	return paths.Home()
}

// SheetsDir returns the directory that holds the markdown sheets.
func SheetsDir() (string, error) {
	d, err := Dir()
	if err != nil {
		return "", err
	}
	return filepath.Join(d, "sheets"), nil
}

var toolName = regexp.MustCompile(`^[a-z0-9][a-z0-9._+-]*$`)

// PathFor returns the on-disk path of a tool's sheet, rejecting names that
// would not be safe as a filename.
func PathFor(tool string) (string, error) {
	tool = strings.ToLower(tool)
	if !toolName.MatchString(tool) {
		return "", fmt.Errorf("invalid tool name %q", tool)
	}
	d, err := SheetsDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(d, tool+".md"), nil
}

// Write renders a report to its sheet, preserving the user's notes below the
// keep-marker when the sheet already exists.
func Write(r analyze.ToolReport, generatedOn string) (string, error) {
	path, err := PathFor(r.Tool)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", err
	}

	keep := defaultKeep
	if old, err := os.ReadFile(path); err == nil {
		if i := strings.Index(string(old), KeepMarker); i >= 0 {
			keep = string(old[i:])
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — personal cheatsheet\n\n", r.Tool)
	fmt.Fprintf(&b, "> Generated by ricorda on %s from your own shell history.\n", generatedOn)
	b.WriteString("> Rescans rewrite everything above the keep-marker; your notes below it stay.\n\n")

	if len(r.HardWon) > 0 {
		b.WriteString("## Hard-won (you fought for these)\n\n")
		for _, h := range r.HardWon {
			loc := ""
			if h.CWD != "" {
				if l := project.Label(h.CWD); l != "" {
					loc = " · in " + l
				}
			}
			fmt.Fprintf(&b, "- `%s`  — took %d attempts%s%s\n", h.Command, h.Attempts, costNote(h), loc)
		}
		b.WriteString("\n")
	}
	if len(r.Hits) > 0 {
		b.WriteString("## Greatest hits\n\n")
		for _, h := range r.Hits {
			fmt.Fprintf(&b, "- `%s`  — ×%d\n", h.Command, h.Count)
		}
		b.WriteString("\n")
	}
	if r.HelpLookups > 0 {
		fmt.Fprintf(&b, "## Help lookups\n\nYou reached for help on `%s` %d time(s). The commands above are the ones that stuck.\n\n", r.Tool, r.HelpLookups)
	}
	b.WriteString(keep)

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

// costNote annotates a hard-won command with its measured price. Only
// journal-certified fights have one; heuristic guesses stay unadorned.
func costNote(h analyze.HardWon) string {
	if !h.Certified {
		return ""
	}
	if h.CostMS < 1000 { // sub-second fights: the badge alone is enough
		return " (certified)"
	}
	return fmt.Sprintf(" (%s of fighting, certified)", analyze.FmtDurMS(h.CostMS))
}

// Read returns the raw markdown of a tool's sheet.
func Read(tool string) (string, error) {
	path, err := PathFor(tool)
	if err != nil {
		return "", err
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// Meta describes one stored sheet.
type Meta struct {
	Tool    string
	Path    string
	ModTime time.Time
}

// List returns every stored sheet, alphabetically.
func List() ([]Meta, error) {
	d, err := SheetsDir()
	if err != nil {
		return nil, err
	}
	dirEntries, err := os.ReadDir(d)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var out []Meta
	for _, e := range dirEntries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		info, err := e.Info()
		if err != nil {
			continue
		}
		out = append(out, Meta{
			Tool:    strings.TrimSuffix(e.Name(), ".md"),
			Path:    filepath.Join(d, e.Name()),
			ModTime: info.ModTime(),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Tool < out[j].Tool })
	return out, nil
}
